apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: vllm-gpu-ccc
spec:
  nodePoolAutoCreation:
    enabled: true
  autoscalingPolicy:
    consolidationDelayMinutes: 3
  priorities:
  - nodepools: [a100-2-pool-a]
  - nodepools: [a100-2-pool-b]
  - nodepools: [a100-2-pool-c]
  - nodepools: [a100-2-pool-f]
  - nodepools: [l4-2-pool-a]
  - nodepools: [l4-2-pool-b]
  - nodepools: [l4-2-pool-c]
  - nodepools: [t4-4-pool-a]
  - nodepools: [t4-4-pool-b]
  - nodepools: [t4-4-pool-c]
