{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dra-driver-noop.serviceAccountName" . }}
  labels:
    {{- include "dra-driver-noop.labels" . | nindent 4 }}
{{- end -}}
